---
caasp-admin:
  vars:
    ansible_user: root

caasp-masters:
  vars:
    ansible_user: root

caasp-workers:
  vars:
    ansible_user: root

soc-deployer:
  vars:
    ansible_user: root

ses_nodes:
  vars:
    ansible_user: root

airship-openstack-compute-workers:
  vars:
    ansible_user: root

airship-openstack-control-workers:
  vars:
    ansible_user: root

airship-ucp-workers:
  vars:
    ansible_user: root

airship-kube-system-workers:
  vars:
    ansible_user: root
