---
# defaults file for suse-airship-deploy

# Location of the kubeconfig file, fetched from velum UI.
kubeconfig_file_path: "{{ socok8s_deploy_config_location }}/kubeconfig"

suse_airship_deploy_packages:
  - ca-certificates
  - make
  - jq
  - nmap
  - uuid-runtime
  - docker
  - curl
  - python2-setuptools
  - python2-pip
  - python-devel

suse_airship_deploy_python_libs:
  - "cmd2<=0.8.7"
  - python-openstackclient
  - python-heatclient

# Keep this until helm is packaged as rpm
helm_download_url: "https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get"

# Airship repos
airship_repos:
  airship-armada:
    src: https://git.openstack.org/openstack/airship-armada.git
  airship-shipyard:
    src: https://git.openstack.org/openstack/airship-shipyard.git
  airship-deckhand:
    src: https://git.openstack.org/openstack/airship-deckhand.git
  airship-pegleg:
    src: https://git.openstack.org/openstack/airship-pegleg.git
  airship-treasuremap:
    src: https://git.openstack.org/openstack/airship-treasuremap.git
  openstack-helm-infra:
    src: https://git.openstack.org/openstack/openstack-helm-infra.git
    version: b55e9b10a72ce5531ae22f15f953b2eb71e6f623
  openstack-helm:
    src: https://git.openstack.org/openstack/openstack-helm.git
    version: 4f94593e870ac879b2d01300cb02485ace58b3ac
